version: "3.8"
services:
    service-socks:
        image: gregoriomomm/multsocks:latest
        container_name: multsocks
        # To tunnel ports to localhost
        # environment: 
           #- SOCKS_CONNECTIONS=1
           # local_port:destination_host:destination_port
           # - SOCKS_1=10013:192.168.248.1:10013  
           # - SOCKS_2=10013:192.168.248.2:10013  
        restart: always   
        networks: 
            - service-net
        ports: 
            - "1080:1080"
            - "3128:3128"
        volumes:
            - source: ./tsocks.conf
              target: /etc/tsocks.conf
              type: bind 

#    service-java:
#       image: service-java:1.0
#       container_name: service-java
#       environment: 
#           - JVM_ARGS=-DsocksProxyHost=service-socks  -DsocksProxyPort=1080
#       restart: always
#       networks: 
#           - service-net
#       ports: 
#           - "9080:9080"
      
       
networks:
     service-net:
         driver: bridge

